version: 0.2

phases:
  build:
    commands:
      - $(aws ecr get-login --no-include-email --region us-east-1)
      - docker build -t my-app:latest .
      - docker tag my-app:latest public.ecr.aws/k2w3e6a8/mysampleapp:latest
  post_build:
    commands:
      - docker push public.ecr.aws/k2w3e6a8/mysampleapp:latest

artifacts:
  files: Dockerfile
